### ISSUE TITLE
置頂全站索引 分散式系統目錄失效

### ISSUE THREAD

**Issue by Darkborderman** [rickhw/rickhw.github.io#11]
在置頂的[全站索引](https://rickhw.github.io/2018/07/08/Index/)貼文

關於[分散式系統](https://rickhw.github.io/categories/DistributedSystems/)連結會導到404, 應該是單純路徑錯誤導致, 正確的是[這個](https://rickhw.github.io/categories/Distributed-Systems/)

**Comment by rickhw** [comment]
fixed
